### ISSUE TITLE
Call to a member function convert() on a non-object	

### ISSUE THREAD

**Issue by rodelta** [AlessandroMinoccheri/cakephp-currency-converter#1]
Hi. Thanks for making this plugin.
I followed the instructions in the readme, but I got this error:
`Call to a member function convert() on a non-object` 

I tried to load the component manually in the controller where I want to use the plugin:
`public $components = array('CurrencyConverter.CurrencyConverter');`
but it gives me an 'Missing component' error.

Any idea why it's behaving this way? I'm sorry if I'm making an stupid mistake, but I couldn't get what I'm doing wrong.
Cheers

**Comment by landi123** [comment]
Hello there, This is a quite nice plugin, and it works, but now i have a question.

For example I have a list of houses with the price on the index view , and each  may have different  currencies for example:

we have 4 houses.

A -> 30 USD
B -> 25 USD
C -> 35 EUR
D - > 40 GBP

So in the index page if the user has selected EUR it should display all  Houses in EUR with correcponding converted price.

??? 

is there a way how can i achieve that

**Comment by AlessandroMinoccheri** [comment]
Yes in your controller you need to parse your result and before print it convert in the language that the user has selected before.

**Comment by landi123** [comment]
Thanx for your reply, im sorry i didnt know how to create it, anyway The point is where exacly to call the function since in the controller the items are parsed in the array  as:

$items = $this->Item->find('all', array('recursive' => 0));	
$this->set('items', $items);
then i just send the variable to the view here i iterate all element from there..

**Comment by AlessandroMinoccheri** [comment]
you can make something like this:
```
$items = $this->Item->find('all', array('recursive' => 0)); 
foreach($items as $item){
    $item['House']['price'] = $this->CurrencyConverter->convert($item['House']['currency'], 'EUR', $item['House']['price'], 1, 1);
}

$this->set('items', $items);

```

In this way you parse every price and convert the price from the currency of it to euro

**Comment by landi123** [comment]
Thankyou! 
you were really helpfull.

Keep up the good work
