### ISSUE TITLE
Is there any Helper to convert directly in View?

### ISSUE THREAD

**Issue by JeanValJeann** [AlessandroMinoccheri/cakephp-currency-converter#11]
Hi,

Im wondering if you plan to add an Helper to convert directly within the view? I'll attempt to do it if you not.

**Comment by AlessandroMinoccheri** [comment]
Hi @JeanValJeann it could be useful to add an Helper, if you want you can try to do it and create a pull request! It could be wonderful to have another contributor on this repository!
Thanks

**Comment by JeanValJeann** [comment]
Hi @AlessandroMinoccheri, Im working on Helper keeeping features and behavior of your Component. To do that I have to refactore your Component and put some methods that Component and Helper will share in a Utility class to not write twice same methods.

Do you mind if:

- I refactore your Component (I keep same testCase to show you that is just refactoring)?
- I create Helper
- I create an Utility class to write methods that Component and Helper will share?

**Comment by AlessandroMinoccheri** [comment]
I think that you can work on my Component as you want.
After you have create the pull request we can think together best approach / refactoring. 
What do you think?

**Comment by JeanValJeann** [comment]
Yep. Im working on, I ll pull request you and we will talk about what's the best way to do.

**Comment by JeanValJeann** [comment]
hi @AlessandroMinoccheri,

In your doc you mention that plugin use https://fixer.io to get currency rate but it doesn't!
Actually plugin is using https://free.currencyconverterapi.com/ to get a currency rate.

By now, I'm now working on the plugin and I was wondering if we could really use https://fixer.io/ (instead of https://free.currencyconverterapi.com/) to get currency rate.

Fixer.io require an API Key. So each plugin's user will have to create his own key (within https://fixer.io/product) before using the plugin. Fixer purpose to get Key for free (https://fixer.io/product) and if wanted Plugin user's can upgrade his acccount...

Could I use definetly Fixer.io?

I just have to write some code to mention API key of plugin's user.

**Comment by AlessandroMinoccheri** [comment]
Hi @JeanValJeann at the moment I think is better to use currencyconverterapi for the reason of the api key that can be a problem of cost after some call to the api.
In the future I will create my own service or an interface to use fixer.io or currencyconverterapi, where developers can decide it from a configuration for example

**Comment by JeanValJeann** [comment]
Helper has been adding to plugin, yet!
