### ISSUE TITLE
Notice (8): Undefined index: dsn

### ISSUE THREAD

**Issue by JeanValJeann** [AlessandroMinoccheri/cakephp-currency-converter#12]
Hi,

I'm using your Component from a Controller. I setted up **save_into_db** to 1 and **hour_difference** to 0.

`$amount = '2100,00';`
`$price = $this->CurrencyConverter->convert('GBP', 'EUR', $amount, 1, 0);`

In this use case I use database at each Component's request time to check if all is allright, but I got an error when Component is attempting to use Database. The error is the following Error:

`
Notice (8): Undefined index: dsn [ROOT\vendor\alessandrominoccheri\CurrencyConverter\src\Controller\Component\CurrencyConverterComponent.php, line 190]
`

In ensureIfExistTable() method at line 190 my Database config seems to not have 'dsn' key. What I'm suppossed to do?

Note that all work fine (Component and Model) but I got an error.

**Comment by AlessandroMinoccheri** [comment]
Which parameter do you have into your configuration?

**Comment by JeanValJeann** [comment]
`[
	'driver' => 'Cake\Database\Driver\Mysql',
	'persistent' => false,
	'host' => 'localhost',
	'username' => 'root',
	'password' => '',
	'database' => 'cakephp-3-currency',
	'timezone' => 'UTC',
	'flags' => [],
	'cacheMetadata' => true,
	'log' => false,
	'quoteIdentifiers' => false,
	'url' => null,
	'name' => 'default'
]`

**Comment by AlessandroMinoccheri** [comment]
Which version of cakephp are you using?

**Comment by AlessandroMinoccheri** [comment]
Have you tried to fill `url` parameter?  I think that null is not a good way for it

**Comment by JeanValJeann** [comment]
I just tryied to fill url parameter as below:

`'url' => 'mysql://root:@localhost/cakephp-3-currency'`

But I still get the same error:

`Undefined index: dsn [ROOT\vendor\alessandrominoccheri\CurrencyConverter\src\Controller\Component\CurrencyConverterComponent.php, line 189]`

Even when fill url parameter up I still not get a 'dsn' key in my Database config to use your Component :(

**Comment by AlessandroMinoccheri** [comment]
dsn isn't a parameter.
I think that is a bug introduced with cakephp 3.6, I'll investigate on it as soon as possible.

**Comment by JeanValJeann** [comment]
Ok @AlessandroMinoccheri  that works.

**Comment by AlessandroMinoccheri** [comment]
Thanks to have open this issue @JeanValJeann
