### ISSUE TITLE
Travis build failed

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [AlessandroMinoccheri/cakephp-currency-converter#17]
Test now are broken, build failed.

I think there is something with new commit @JeanValJeann, what do you think?

**Comment by JeanValJeann** [comment]
Sorry, I haven't had time to check this out. I ll do it sooooon.

**Comment by AlessandroMinoccheri** [comment]
Great! Thanks @JeanValJeann

**Comment by AlessandroMinoccheri** [comment]
Closed by #18
