### ISSUE TITLE
PDO EXCEPTIONS ON CAKEPHP 3

### ISSUE THREAD

**Issue by back2back** [AlessandroMinoccheri/cakephp-currency-converter#5]
The plugin is broken on my machine. Seems to be the fact that the table columns are using reserved keywords for mysql i.e (from , to) . Changing these to something else removes SQLSTATE[42000]; but other errors creep up. Used your example @AlessandroMinoccheri but still getting no such stream errors for requiring bootstrap. 

Hope this helps someone

**Comment by AlessandroMinoccheri** [comment]
I will check it as soon as possible.
Thanks

**Comment by AlessandroMinoccheri** [comment]
Fixed in release v2.0.2
