### ISSUE TITLE
composer install error

### ISSUE THREAD

**Issue by quasiperfect** [AlessandroMinoccheri/cakephp-currency-converter#6]
Generating autoload files
> Cake\Composer\Installer\PluginInstaller::postAutoloadDump
Script Cake\Composer\Installer\PluginInstaller::postAutoloadDump handling the po
st-autoload-dump event terminated with an exception

  [RuntimeException]
  Unable to get primary namespace for package alessandrominoccheri/cakephp-cu
  rrency-converter.
  Ensure you have added proper 'autoload' section to your plugin's config as
  stated in README on https://github.com/cakephp/plugin-installer

**Comment by AlessandroMinoccheri** [comment]
Can you please show me what have you tried?
Thanks

**Comment by quasiperfect** [comment]
i created a project
https://github.com/cakephp/app
composer create-project --prefer-dist cakephp/app testapp
then i tried to install your plugin
composer require "alessandrominoccheri/cakephp-currency-converter:3.0.*@dev"

**Comment by AlessandroMinoccheri** [comment]
Hi,
sorry for delay.
I have fix the composer bug and now it works fine with new release 2.0.3
to install you need to use now:
composer require "alessandrominoccheri/cakephp-currency-converter"

Thanks
